Repository githubschool/good-vibes, pull requests merged in 2019-12, with the labels that each got.

#20 Added a great description of JDB
  _posts/0000-01-11-johndavidback.md
Labels: documentation, enhancement

#18 changed my caption
  _posts/0000-01-07-LucasFrazier.md
Labels: enhancement

#14 Update 0000-01-36-rjwink.md
  _posts/0000-01-36-rjwink.md
Labels: documentation

#30 Update caption of my slide
  _posts/0000-01-26-EduSemensati.md
Labels: enhancement

#9 Updating Josh's slide for important content
  _posts/0000-01-08-joshuarose.md
Labels: content

#15 Updated caption
  _posts/0000-01-03-nogorilla.md
Labels: content
